name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório para o Runner, perimitindo que os scripts possam utilizar o conteúdo do repositório.
      - uses: actions/checkout@v4

      - name: Setup do node.js
        uses: actions/setup-node@v4.0.3
        with:
          node_version: 20.16.0
